[package]
authors = ["Bob Gardner <bob.hn.gardner@gmail.com>"]
edition = "2018"
name = "rust-playground"
version = "0.1.0"

[dependencies]
rustc-serialize = "0.3.24"
chrono = "0.4.10"
nix = "0.17.0"
tempfile = "3.1.0"
