name: C++ Playground

on:
  pull_request:
    paths:
      - "!*"
      - ".github/workflows/cpp_playground_ci.yml"
      - "cpp_playground/**"
      - "!cpp_playground/.gitignore"
      - "!cpp_playground/**.md"
  push:
    branches: [master]
    paths:
      - "!*"
      - ".github/workflows/cpp_playground_ci.yml"
      - "cpp_playground/**"
      - "!cpp_playground/.gitignore"
      - "!cpp_playground/**.md"

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Setup
        run: |
          pip install invoke
          cd cpp_playground && invoke setup
          sudo apt-get install ninja-build
      - name: Build
        run: cd cpp_playground && invoke build
      - name: Test
        run: cd cpp_playground && invoke test

  fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Setup
        run: |
          pip install invoke
          cd cpp_playground && invoke setup
      - name: Check formatting
        run: cd cpp_playground && invoke fmt --check

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Setup
        run: |
          pip install invoke
          cd cpp_playground && invoke setup
      - name: Lint
        run: cd cpp_playground && invoke lint
